// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtsI7mzVb3bg2IFWX7taBIvDff7eszN9M',
    appId: '1:33636562901:web:a8926fe280d1925a482f5c',
    messagingSenderId: '33636562901',
    projectId: 'petfinder-db610',
    authDomain: 'petfinder-db610.firebaseapp.com',
    storageBucket: 'petfinder-db610.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0F260ACdHMLSqy3wvhLDSU2FeojqqoC8',
    appId: '1:33636562901:android:628bb164df84ed7f482f5c',
    messagingSenderId: '33636562901',
    projectId: 'petfinder-db610',
    storageBucket: 'petfinder-db610.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4axWc-h0rRqaiR39jJkkETpo8wu9JdbU',
    appId: '1:33636562901:ios:1ed5c661a12aaed3482f5c',
    messagingSenderId: '33636562901',
    projectId: 'petfinder-db610',
    storageBucket: 'petfinder-db610.firebasestorage.app',
    iosBundleId: 'com.example.petFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4axWc-h0rRqaiR39jJkkETpo8wu9JdbU',
    appId: '1:33636562901:ios:1ed5c661a12aaed3482f5c',
    messagingSenderId: '33636562901',
    projectId: 'petfinder-db610',
    storageBucket: 'petfinder-db610.firebasestorage.app',
    iosBundleId: 'com.example.petFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtsI7mzVb3bg2IFWX7taBIvDff7eszN9M',
    appId: '1:33636562901:web:0b64e90ebf4796df482f5c',
    messagingSenderId: '33636562901',
    projectId: 'petfinder-db610',
    authDomain: 'petfinder-db610.firebaseapp.com',
    storageBucket: 'petfinder-db610.firebasestorage.app',
  );

}